config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users

  root to: 'records#home'

  resources :records, only: %i[index show]

  resources :user_sets, only: %i[show create index] do
    resources :set_items, only: [:create]
  end

  get '/about', to: 'static_pages#about'
  get '/contact', to: 'static_pages#contact'
  get '/become_a_partner', to: 'static_pages#become_a_partner'
  get '/terms', to: 'static_pages#terms'
  get '/base_template', to: 'static_pages#base_template'
end

app/views/shared/_add_to_set.html.haml
= render partial: "shared/add_to_set_logged_#{logged_in ? 'in' : 'out'}",
         locals: { record_id: record.id }

app/views/shared/_add_to_set_logged_in.html.haml
%span.add-to-set{ 'data-record-id': record_id } +
.add-to-set-popup.logged-in
  %ul.sets-container
  %form
    %label
      New set
      %input.add-to-new-set-name{ type: 'text' }/
    %input.add-to-new-set-submit{ 'data-record-id': record_id, type: 'submit', value: 'Create' }/

app/views/shared/_add_to_set_logged_out.html.haml
%span.add-to-set +
.add-to-set-popup
  %p
    You need to #{link_to "sign-in", new_user_session_path} or
    #{link_to "sign-up", new_user_registration_path} to save items

app/views/shared/_breadcrumbs.html.haml
- unless @breadcrumbs.nil?
	%ul.breadcrumbs
		%li= link_to 'DigitalNZ Home', root_url
		- @breadcrumbs.each do |label, link|
			%li= link_to label, link

app/views/shared/_flash.html.haml
- if flash.present?
  .grid-container
    - flash.each do |name, msg|
      .callout{ 'data-closable': true, class: name }
        %p= msg
        %button.close-button{ 'aria-label': 'Dismiss alert', 'data-close': true, type: 'button' }
          %span{ 'aria-hidden': true }
            &times;

app/views/shared/_footer.html.haml
%footer
  .grid-container
    %nav
      %ul.menu.align-center
        %li= link_to 'Become a Partner', become_a_partner_path
        %li= link_to 'Contact', contact_path
        %li= link_to 'Terms of use', terms_path

= javascript_include_tag 'application'
= javascript_pack_tag 'application'

app/views/shared/_head.html.haml
%head
  %title= site_title(yield(:title))
  %meta{ charset: 'utf-8' }/
  %meta{ content: 'width=device-width, initial-scale=1.0', name: 'viewport' }/
  = stylesheet_link_tag 'application'
  = csrf_meta_tags
  = csp_meta_tag

app/views/shared/_menu.html.haml
%header
  .title-bar{ 'data-hide-for': 'medium', 'data-responsive-toggle': 'responsive-menu' }
    %button.menu-icon{ 'data-toggle': 'responsive-menu', type: 'button' }
    .title-bar-title Menu

  .top-bar#responsive-menu
    .top-bar-left
      %ul.dropdown.menu{ 'data-dropdown-menu': true }
        %li.menu-text= t('site_title')
        %li= link_to 'Home', root_url
        %li= link_to 'Contact', '/contact'
        %li= link_to 'About', '/about'
        - unless current_page? root_url
          %li
            = form_with url: records_path, local: false, class: 'input-group' do |form|
              = form.hidden_field :tab, value: params[:tab] if params[:tab].present?
              = form.text_field search.text,
                  class: 'input-group-field',
                  placeholder: t('records.enter_search')
              .input-group-button
                = form.submit 'Search', class: 'button'
    .top-bar-right
      %ul.dropdown.menu{ 'data-dropdown-menu': '' }
        - if user_signed_in?
          %li.has-submenu
            %a= current_user.email.split('@').first
            %ul.submenu.menu.vertical{ 'data-submenu': true }
              %li= link_to 'Edit profile', edit_user_registration_path
              %li= link_to 'Logout', destroy_user_session_path, method: :delete
        - else
          %li= link_to 'Sign up', new_user_registration_path
          %li= link_to 'Login', new_user_session_path

app/views/shared/_search.html.haml
= form_with url: records_path, method: :get, local: true, class: 'search clearfix' do |form|
  = form.hidden_field 'tab', params[:tab] if params[:tab].present?
  = form.text_field search.text, class: 'search-input', placeholder: t('records.enter_search')
  = form.submit 'Search', class: 'search-button'