config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users

  root to: 'records#home'

  resources :records, only: %i[index show]

  resources :user_sets, only: %i[show create index] do
    resources :set_items, only: [:create]
  end

  get '/about', to: 'static_pages#about'
  get '/contact', to: 'static_pages#contact'
  get '/become_a_partner', to: 'static_pages#become_a_partner'
  get '/terms', to: 'static_pages#terms'
  get '/base_template', to: 'static_pages#base_template'
end

app/controllers/user_sets_controller.rb
# frozen_string_literal: true

class UserSetsController < ApplicationController
  before_action :authenticate_user!, except: [:show]

  def show
    @user_set = Supplejack::UserSet.find(params[:id])
    @records = @user_set.items
    @search = search(params[:search])
  end

  def index
    sets = current_sj_user.sets.map do |set|
      { name: set.name, id: set.id, items_count: set.count }
    end

    respond_to do |format|
      format.js do
        render json: { sets: sets }
      end
    end
  end

  def create
    render nothing: true, status: 500 if params[:user_set].nil?

    user_set = current_sj_user.sets.build(user_set_params[:user_set].to_h)
    user_set.records = [{ record_id: user_set_params[:record_id] }] if user_set_params[:record_id]
    user_set.save

    respond_to do |format|
      format.html { redirect_to user_sets_path }
      format.js do
        render json: { set_id: user_set.id }.to_json
      end
    end
  end

  private

    def user_set_params
      params.require(:user_set).permit(:name)
      params.permit(:record_id, :name, user_set: [:name])
    end
end

app/views/user_sets/_set_item.html.haml
.gallery-record
  = record_thumbnail(item, search)
  = link_to truncate(item.title, length: 20), record_path(item.record_id, search.options)

app/views/user_sets/show.html.haml
- title @user_set.name.truncate(40)
- content_for(:body_class) {'user_set'}
.container.record
  %figure
    .gallery-container
      %span.gallery-spinner
      - @records.each do |r|
        = render partial: 'set_item', locals: {item: r, search: @search}
      .infinite-spinner#second-spinner
  .about
    = attribute(@user_set, :name, label: false, tag: 'h1')
    %p
      %span.field-label= t('user_sets.creator')
      = @user_set.user&.name

    = attribute(@user_set, :tags,
        label_tag: 'span',
        label_class: 'field-label',
        trans_key: 'user_sets.date')

    = attribute(@user_set, :description,
        label_tag: 'span',
        label_class: 'field-label',
        trans_key: 'user_sets.description',
        limit: 1000)